SHELL=/bin/bash
build:
	cd jofisaes-image-morpher-js && yarn
test:
	yarn add sharp --ignore-engines; \
 	npm test
coverage-npm:
	cd jofisaes-image-morpher-js && npm run coverage
security-npm:
	cd jofisaes-image-morpher-js && npm run snyk
